### ISSUE TITLE
problem installing javascripting learnyounde

### ISSUE THREAD

**Issue by catfriend** [nodeschool/seattle#21]
see gist
https://gist.github.com/catfriend/31e1033cc44c043aa5d8
Thanks

**Comment by housepage** [comment]
You must precede the command with sudo as in:

`sudo npm install -g javascripting learnyounode`

This is because the "-g" option instructs it to install the library
globally which means it is installed for all users and thus requires super
user access to install like most programs. Running a command proceeded by
the sudo command causes the program to be run with super user permissions.


Sincerely,

Peaches

On Wed, Mar 25, 2015 at 11:56 AM, Elizabeth <notifications@github.com>
wrote:

> see gist
> https://gist.github.com/catfriend/31e1033cc44c043aa5d8
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/seattle/issues/21>.
>



-- 
Yours Pagely,
Andrew E. Gall

"Peaches come from a can,
they were put there by a man
In a factory downtown
If I had my little way,
I'd eat peaches every day."
- Thomas Edison

http://imgs.xkcd.com/comics/compiler_complaint.png

**Comment by catfriend** [comment]
Thanks, done.

Date: Wed, 25 Mar 2015 12:01:15 -0700
