### ISSUE TITLE
April 7th, 2015 Call for Mentors

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#22]
We will need about 30 mentors for this event (150 max capacity). If you can commit to April 7th, 2015 from 6-9pm let us know. I will update this list as we get more mentors.

- [x] Farrin Reid @blakmatrix / Organizer
- [x] Louis K @louisnk 
- [x] Josh Benner @libreninja 
- [x] Chris @chrisvariety 
- [x] Keith @keithjia 
- [x] Seth Vincent @sethvincent 
- [x] Manu ??? @manuisfunny 
- [x] Josh ??? @joshgit
- [x] Luke Swart @LukeSwart 
- [x] Jordan Ball @cjordanball  
- [ ] ? 
- [ ] ?
- [ ] ?  
- [ ] ?
- [ ] ?  
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?  
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ? 
- [ ] ?

**Comment by louisnk** [comment]
I'm in.

**Comment by libreninja** [comment]
me too

**Comment by chrisvariety** [comment]
me three! new to this, are there any resources to check out beforehand?

**Comment by keithjia** [comment]
I'd like to help out as a mentor; same question as Christ, what is the process like as a mentor?

**Comment by libreninja** [comment]
@chrisvariety @keithjia check out the core workshops at [nodeschool](http://nodeschool.io/).

Most attendees have been working through javascripting or learnyounode.  We had a couple of people looking at more advanced workshops.  But if you are familiar with how any of the workshops works, you'll be able to help learners with any of them.

**Comment by libreninja** [comment]
@keithjia, we typically start with a demo that shows people how to install a workshop, followed by a demo of the first task in the workshop.  After that, people jump in and get to work.  Mentors typically wander through the room helping people with whatever questions they have.

There are a number of things people will ask you about.  Some will need help installing and running node and nodeschool workshops.  Others are unfamiliar with the command line, and may need guidance to get started. For example you might encourage windows users to create a working directory in their $HOME directory, rather than working out of 'c:\'  (or wherever they installed node).  Others will need help finding and setting up a reasonable text editor.  And then of course there will be javascript/node.js questions.

Expect questions about anything js or node related from "what is process.argv?" and "what does async mean?" to "what is a closure?" etc...  Going through the workshop yourself will help you understand what concepts people will encounter and what they may have trouble with.  

There have been lulls in activity for whatever reason.  Periodically asking "how is it going?" often yields a question or two, even if someone doesn't *appear* to need help.  Encourage people to ask for help and to celebrate their accomplishments.  This isn't study hall in a library, we can and should make some noise.

**Comment by louisnk** [comment]
@chrisvariety glad to see you found this!
@keithjia like @libreninja said, it's pretty simple! Thanks for that great explanation.

I like to think of it as: you'll definitely have a good time, and people will love you for explaining why that variable they assigned something to in their callback is undefined later in the script.

**Comment by keithjia** [comment]
Great walk through, exactly what I was looking for, thank you @libreninja

**Comment by sethvincent** [comment]
I thought I couldn't make it to this one, but I can, so I'm in.

**Comment by blakmatrix** [comment]
@libreninja @chrisvariety @keithjia @louisnk Awesome! Thanks for signing up, that said we still need more mentors, I'm thinking will need a minimum of 15 to not be over-encumbered, do you all have any friends that would like to mentor at the event.

@sethvincent Glad to hear it, I was worried about having to figure out who would run the tutorial :) glad to have you at this one!

**Comment by blakmatrix** [comment]
could people also RT this https://twitter.com/nodeschool_sea/status/584035212583133184

**Comment by manuisfunny** [comment]
I'd like to be a mentor.  I only have a year of experience, but I have created some web apps using node.js and the MEAN stack (MongoDB, ExpressJS, AngularJS, NodeJS).  

I will also work through the core nodeschool workshops before April 7 to prepare for questions.

**Comment by joshgit** [comment]
I'll mentor.

**Comment by libreninja** [comment]
Adding @manuisfunny @joshgit to the mentor list.

**Comment by libreninja** [comment]
It looks like we could still use more mentors for tomorrow.  Please reach out to friends, colleauges etc...  

Retweet the following (or share your own tweets so we can RT them too):
- https://twitter.com/nodeschool_sea/status/584035212583133184
- https://twitter.com/libreninja/status/585104657581613058

**Comment by cjordanball** [comment]
Sign me up!

Jordan Ball

**Comment by LukeSwart** [comment]
Count me in :-)

Luke Swart

**Comment by sethvincent** [comment]
@LukeSwart added to the list!

**Comment by blakmatrix** [comment]
Hey all, I will be arriving at Moz around 5:30. It'd be great if we can get a few last minute mentors just in case--reach out to your friends and coworkers. See you at the event!

**Comment by blakmatrix** [comment]
https://github.com/nodeschool/seattle/issues/28
Thanks everyone for being such awesome mentors!
