### ISSUE TITLE
April 7th, 2015 NodeSchool Event Debrief

### ISSUE THREAD

**Issue by blakmatrix** [nodeschool/seattle#28]
Mentors & Students: Please comment on how this event went -- What went well? What could go better? Any flags, how did the workshoppers go?, etc.
We want to make future events better and more accessible to all, so your feed back is valuable.

Thanks in advance!

**Comment by libreninja** [comment]
One thing that stood out to me was that the presentation in the middle of the event was disruptive.  The person I was helping was starting to make real progress but had to stop everything to switch to a listening context for the speaker.

I would prefer that talks be short, node/js focused and only happen at the beginning of the event if at all.

**Comment by keithjia** [comment]
I like the middle talk. It sort of livened things up a bit, picking the
energy up when things were dying down.

I appreciate Josh's comment and his dedication to the person. And of
course, there are times when we just have to get through a technique. But
if we think about what made node.js special, a large part isn't the
technology itself, it's the community surrounding it. So I think, more
people interaction the better. We might even flip the "school" concept
around and have the "students" get up there and teach something they
learned?

On Thu, Apr 16, 2015 at 10:06 AM, Josh Benner <notifications@github.com>
wrote:

> One thing that stood out to me was that the presentation in the middle of
> the event was disruptive. The person I was helping was starting to make
> real progress but had to stop everything to switch to a listening context
> for the speaker.
>
> I would prefer that talks be short, node/js focused and only happen at the
> beginning of the event if at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/seattle/issues/28#issuecomment-93786508>.
>



-- 
Keith Jia
(310) 408 9637 Cell

**Comment by chrisvariety** [comment]
Maybe just a quick heads up announcement "talk in 10 minutes"  "talk in 5 minutes" would help disrupt a little less, as you could find a natural stopping point--

**Comment by blakmatrix** [comment]
I felt the talk was good in general, however I did feel like many students did get interrupted being just an hour in, also many people left afterwards even though there was still an hour of time left. in general on weekends unless the talk is short and in the beginning or end I just don't think there will be enough time for folks to really get through a good chunk of the workshoppers.

**Comment by libreninja** [comment]
Good points @keithjia.  I also enjoyed the talk.  I've been thinking about novel applications for distributing local information like that, ever since.

But compared with my experience at the last 2 events, this one felt like it had just started before the talk, and was over a few minutes after.   Maybe it's a weeknight thing or whatever; we don't have enough data points to know.  We can work on announcements and something compelling or fun on the agenda to help re-engage people after a context switch.

I like the idea of flipping things around and finding ways to encourage collaboration and interaction. 
* Build your own nodeschool, 'build a workshop' hackathon
* Publish your own npm module
