### ISSUE TITLE
Becoming a co-organizer

### ISSUE THREAD

**Issue by JustinBeckwith** [nodeschool/seattle#44]
Greetings folks!  After attending my first NodeSchool down in SF last week, I'm really interested in helping co-organize a few Seattle events.  I work over at Google, so getting access to a space to host the events is no problem.  

Any interest in working together to set up a Seattle event?

**Comment by sethvincent** [comment]
That would be great! I've been planning to get more Seattle events happening this year and would be happy to team up.

**Comment by daveskull81** [comment]
This sounds awesome. I have always really enjoyed the NodeSchool events I've attended here. I would be happy to help make some happen here in Seattle this year.

**Comment by sethvincent** [comment]
@JustinBeckwith @daveskull81 I started a planning issue for putting together the first event since we've been on break: https://github.com/nodeschool/seattle/issues/45

**Comment by satanas** [comment]
Hey @JustinBeckwith, I work at Groupon and we're very interested in co-organizing a few NodeSchools in Seattle too. I know it's being a while since you created this issue but if you're still interested let us know. I think we could start working together aiming for something at the end of the year.

cc @Xabadu

**Comment by JustinBeckwith** [comment]
Yup - lets do it!
